name: WordPress Plugin Release

on:
  push:
    tags:
      - 'v*'

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare plugin folder
        run: |
          SLUG=xyz-map-gallery
          mkdir $SLUG
          rsync -av \
            --exclude='.git*' \
            --exclude='.github' \
            --exclude='tests' \
            --exclude='*.yml' \
            --exclude='README-en.md' \ 
            --exclude='README-pl.md'\ 
            --exclude='smartftp.json' \
            --exclude='.gitattributes' \ 
            --exclude='.gitignore' \
            ./ $SLUG/

      - name: Zip it
        run: |
          SLUG=xyz-map-gallery
          zip -r $SLUG.zip $SLUG
